version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/.github/actions/setup-python"
    schedule:
      interval: daily
    groups:
      actions:
        patterns:
          - "*"
